// AUTO-GENERATED from design/tokens.json by scripts/build-tokens.mjs. Do not edit.
// Concrete resolved values (aliases flattened) for use in the MUI theme.
export const tokens = {
	"color.brand.gold": "#C8AA6E",
	"color.brand.goldHover": "#F0E6D2",
	"color.brand.goldDark": "#785A28",
	"color.brand.teal": "#0AC8B9",
	"color.brand.tealHover": "#2DE0D2",
	"color.brand.tealDark": "#0A6E68",
	"color.brand.hextech": "#CDFAFA",
	"color.bg.base": "#0A1428",
	"color.bg.gradientTop": "#12233F",
	"color.bg.surface": "#101F38",
	"color.bg.surfaceHover": "#16294A",
	"color.border.subtle": "rgba(200, 170, 110, 0.18)",
	"color.border.strong": "rgba(200, 170, 110, 0.38)",
	"color.text.primary": "#F0E6D2",
	"color.text.secondary": "#A09B8C",
	"color.text.muted": "rgba(240, 230, 210, 0.45)",
	"color.state.success": "#2FCB8A",
	"color.state.error": "#E84057",
	"color.semantic.primary": "#0AC8B9",
	"color.semantic.secondary": "#C8AA6E",
	"space.1": "4px",
	"space.2": "8px",
	"space.3": "12px",
	"space.4": "16px",
	"space.6": "24px",
	"space.8": "32px",
	"radius.sm": "6px",
	"radius.md": "10px",
	"radius.lg": "16px",
	"radius.pill": "999px",
	"shadow.card": "0 8px 30px rgba(0, 0, 0, 0.45)",
	"shadow.glowTeal": "0 0 24px rgba(10, 200, 185, 0.35)",
	"shadow.glowGold": "0 0 22px rgba(200, 170, 110, 0.30)",
	"font.family.base": "Roboto, system-ui, -apple-system, 'Segoe UI', sans-serif",
	"font.family.display": "Roboto, system-ui, -apple-system, 'Segoe UI', sans-serif",
	"font.weight.regular": "400",
	"font.weight.medium": "500",
	"font.weight.bold": "700",
	"font.weight.black": "900",
} as const;

// var(--token) references for use in CSS-in-JS / raw CSS.
export const cssVar = {
	"color.brand.gold": "var(--color-brand-gold)",
	"color.brand.goldHover": "var(--color-brand-goldHover)",
	"color.brand.goldDark": "var(--color-brand-goldDark)",
	"color.brand.teal": "var(--color-brand-teal)",
	"color.brand.tealHover": "var(--color-brand-tealHover)",
	"color.brand.tealDark": "var(--color-brand-tealDark)",
	"color.brand.hextech": "var(--color-brand-hextech)",
	"color.bg.base": "var(--color-bg-base)",
	"color.bg.gradientTop": "var(--color-bg-gradientTop)",
	"color.bg.surface": "var(--color-bg-surface)",
	"color.bg.surfaceHover": "var(--color-bg-surfaceHover)",
	"color.border.subtle": "var(--color-border-subtle)",
	"color.border.strong": "var(--color-border-strong)",
	"color.text.primary": "var(--color-text-primary)",
	"color.text.secondary": "var(--color-text-secondary)",
	"color.text.muted": "var(--color-text-muted)",
	"color.state.success": "var(--color-state-success)",
	"color.state.error": "var(--color-state-error)",
	"color.semantic.primary": "var(--color-semantic-primary)",
	"color.semantic.secondary": "var(--color-semantic-secondary)",
	"space.1": "var(--space-1)",
	"space.2": "var(--space-2)",
	"space.3": "var(--space-3)",
	"space.4": "var(--space-4)",
	"space.6": "var(--space-6)",
	"space.8": "var(--space-8)",
	"radius.sm": "var(--radius-sm)",
	"radius.md": "var(--radius-md)",
	"radius.lg": "var(--radius-lg)",
	"radius.pill": "var(--radius-pill)",
	"shadow.card": "var(--shadow-card)",
	"shadow.glowTeal": "var(--shadow-glowTeal)",
	"shadow.glowGold": "var(--shadow-glowGold)",
	"font.family.base": "var(--font-family-base)",
	"font.family.display": "var(--font-family-display)",
	"font.weight.regular": "var(--font-weight-regular)",
	"font.weight.medium": "var(--font-weight-medium)",
	"font.weight.bold": "var(--font-weight-bold)",
	"font.weight.black": "var(--font-weight-black)",
} as const;

export type TokenName = keyof typeof tokens;
